=== julElliot/Java_Lab3/src/data/client.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema elementFormDefault="qualified"
           xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="clients" type="clientsType"/>
    <xs:complexType name="tableType">
        <xs:sequence>
            <xs:element type="xs:integer" name="table-id"/>
            <xs:element type="xs:integer" name="number"/>
            <xs:element type="xs:boolean" name="is-free"/>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="clientType">
        <xs:sequence>
            <xs:element type="xs:integer" name="id"/>
            <xs:element type="xs:string" name="first-name"/>
            <xs:element type="xs:string" name="last-name"/>
            <xs:element type="xs:double" name="money"/>
            <xs:element type="tableType" name="table" minOccurs="0"/>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="clientsType">
        <xs:sequence>
            <xs:element type="clientType" name="client" maxOccurs="unbounded" minOccurs="0"/>
        </xs:sequence>
    </xs:complexType>
</xs:schema>

=== julElliot/Java_Lab3/src/data/client.xml
<?xml version="1.0" encoding="UTF-8"?>
<clients xmlns:xs="http://www.w3.org/2001/XMLSchema-instance"
         xs:noNamespaceSchemaLocation="client.xsd">
    <client>
        <id>1</id>
        <first-name>FirstName1</first-name>
        <last-name>LastName1</last-name>
        <money>1000</money>
        <table>
            <table-id>1</table-id>
            <number>1</number>
            <is-free>true</is-free>
        </table>
    </client>
    <client>
        <id>4</id>
        <first-name>FirstName4</first-name>
        <last-name>LastName4</last-name>
        <money>800</money>
    </client>
    <client>
        <id>3</id>
        <first-name>FirstName3</first-name>
        <last-name>LastName3</last-name>
        <money>700</money>
        <table>
            <table-id>3</table-id>
            <number>3</number>
            <is-free>true</is-free>
        </table>
    </client>
    <client>
        <id>2</id>
        <first-name>FirstName2</first-name>
        <last-name>LastName2</last-name>
        <money>1100</money>
        <table>
            <table-id>2</table-id>
            <number>2</number>
            <is-free>true</is-free>
        </table>
    </client>
    <client>
        <id>5</id>
        <first-name>FirstName5</first-name>
        <last-name>LastName5</last-name>
        <money>100</money>
    </client>
</clients>
